#!/usr/bin/env python3
"""Reproduce notices for all external packages in Cargo.lock, including test/target dependencies."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parent.parent
FALLBACKS = {
    ("m68000", "0.2.3"): "m68000-0.2.3-MPL-2.0.txt",
    ("jsonschema-regex", "0.49.1"): "jsonschema-0.49.1-MIT.txt",
    ("jsonschema-value", "0.49.1"): "jsonschema-0.49.1-MIT.txt",
    ("uuid-simd", "0.8.0"): "simd-0.8.0-MIT.txt",
    ("vsimd", "0.8.0"): "simd-0.8.0-MIT.txt",
}


def generate():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"], cwd=ROOT))
    lock = tomllib.loads((ROOT / "Cargo.lock").read_text())
    checksums = {(p["name"], p["version"]): p["checksum"]
                 for p in lock["package"] if "checksum" in p}
    sources = json.loads((ROOT / "licenses/upstream/sources.json").read_text())
    texts = {}
    lines = ["# Third-party notices", "",
             "Generated by `python3 scripts/third_party_notices.py` from the locked graph.",
             "Includes build, test, and optional target dependencies; a particular binary may use a subset.",
             "The project's MIT OR Apache-2.0 license does not replace these dependency licenses.", "",
             "The unmodified MPL-2.0-covered m68000 0.2.3 source is available at",
             "<https://static.crates.io/crates/m68000/m68000-0.2.3.crate> and as",
             "`third-party-source/m68000-0.2.3.crate` in assembled binary distributions.",
             "Recipients retain their rights to that source under MPL-2.0.", ""]
    packages = sorted((p for p in metadata["packages"] if p["source"]),
                      key=lambda p: (p["name"], p["version"]))
    if set(checksums) != {(p["name"], p["version"]) for p in packages}:
        raise ValueError("metadata does not cover every locked registry package")
    for p in packages:
        key = (p["name"], p["version"])
        root = Path(p["manifest_path"]).parent
        paths = sorted(f for f in root.rglob("*") if f.is_file()
                       and ".github" not in f.parts
                       and f.name.lower().startswith(("license", "licence", "copying", "copyright", "notice", "authors", "unlicense")))
        origins = [(str(f.relative_to(root)), f.read_text()) for f in paths]
        if key in FALLBACKS:
            name = FALLBACKS[key]
            origins.append((sources[name], (ROOT / "licenses/upstream" / name).read_text()))
        if not origins or not p["license"]:
            raise ValueError(f"missing license evidence: {key}")
        name, version = key
        lines += [f"## {name} {version}", "", f"License: `{p['license']}`.",
                  f"Authors: {', '.join(p['authors']) or 'See the retained notices below.'}",
                  f"Source: <https://static.crates.io/crates/{name}/{name}-{version}.crate>",
                  f"SHA-256: `{checksums[key]}`", ""]
        for origin, contents in origins:
            digest = hashlib.sha256(contents.encode()).hexdigest()
            texts[digest] = contents
            lines.append(f"- {origin}: [notice {digest[:16]}](#notice-{digest[:16]})")
        lines.append("")
    for digest, contents in sorted(texts.items()):
        lines += [f"## Notice {digest[:16]}", "", "````text", contents.rstrip(), "````", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "THIRD_PARTY_NOTICES.md"
    data = generate()
    if args.check:
        if output.read_text() != data:
            raise SystemExit("Third-party notices are stale; regenerate and review them.")
        print("Third-party notices match the locked dependency graph.")
    else:
        output.write_text(data)


if __name__ == "__main__":
    main()
